#!/bin/bash
# Rival Ultah 

clear
blue='\e[0;34'
cyan='\e[0;36m'
green='\e[0;34m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'

echo -e $white"===================================================="
echo -e $red"  ==                 Dari Firzii                    =="
echo -e $white"==          Selamat Ulang Tahun Kontol            =="
echo -e $red"  ==        Jangan Lupa Kita Ke Deep Web Su         =="
echo -e $white"==  Dan Jangan Lupa Kita Makan² Gue Laper Nih :v  =="
echo -e $red"  ===================================================="

exit
